# Generated by Django 5.0.4 on 2025-08-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
