# Generated by Django 5.0.4 on 2025-08-26 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_alter_categorymodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('ho_address', models.TextField(blank=True, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('social_media_address', models.URLField(blank=True, null=True)),
                ('pancard_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gstin_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tan_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cin_no', models.CharField(blank=True, max_length=21, null=True, unique=True)),
                ('sez_company', models.CharField(blank=True, max_length=255, null=True)),
                ('csc_funding_company', models.CharField(blank=True, max_length=255, null=True)),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.businesscategorymodel')),
            ],
            options={
                'verbose_name': 'KYC Detail',
                'verbose_name_plural': 'KYC Details',
            },
        ),
        migrations.CreateModel(
            name='BankDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('kyc_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='management_app.kycdetailsmodel')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('Vendor Location', 'Vendor Location'), ('View', 'View'), ('Internal Location', 'Internal Location'), ('Customer Location', 'Customer Location'), ('Inventory Loss', 'Innventory Loss'), ('Production', 'Production'), ('Transit Location', 'Transit Location')], max_length=255)),
                ('is_a_scrap_location', models.BooleanField(default=False)),
                ('is_a_return_location', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('removal_strategy', models.CharField(blank=True, choices=[('First In First Out (FIFO)', 'First In First Out (FIFO)'), ('Last In First Out (LIFO)', 'Last In First Out (LIFO)'), ('First Expiry First Out (FEFO)', 'First Expiry First Out (FEFO)')], max_length=255, null=True)),
                ('external_note', models.TextField(blank=True, null=True)),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.locationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumbersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('best_before_date', models.DateTimeField(blank=True, verbose_name='Best before Date')),
                ('removal_date', models.DateTimeField(blank=True, verbose_name='Removal Date')),
                ('end_of_life', models.DateTimeField(blank=True, verbose_name='End Of Life Date')),
                ('alert_time', models.DateTimeField(blank=True, verbose_name='Alert Date')),
                ('is_repacked', models.BooleanField(default=False, verbose_name='Repacked')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='management_app.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.FloatField(default=0.0, verbose_name='On Hand Quantity')),
                ('counted_quantity', models.FloatField(default=0.0)),
                ('reserved_quantity', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.productmodel')),
                ('location_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.locationmodel')),
                ('serialno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.serialnumbersmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='kycdetailsmodel',
            index=models.Index(fields=['firm_name'], name='management__firm_na_89ef16_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdetailsmodel',
            index=models.Index(fields=['business_category'], name='management__busines_6afe72_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdetailsmodel',
            index=models.Index(fields=['gstin_no'], name='management__gstin_n_b505d5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetailsmodel',
            index=models.Index(fields=['bank_name'], name='management__bank_na_9ba6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetailsmodel',
            index=models.Index(fields=['account_number'], name='management__account_48645b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetailsmodel',
            index=models.Index(fields=['ifsc_code'], name='management__ifsc_co_03c633_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['created_at'], name='idx_inventory_created_at'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product'], name='idx_inventory_product'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['location_stock'], name='idx_inventory_location'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['serialno'], name='idx_inventory_serialno'),
        ),
    ]
