# Generated by Django 5.0.4 on 2025-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_usermodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.ManyToManyField(blank=True, to='user_app.addressmodel'),
        ),
    ]
